MOD_NAME:=ddelib

CSRC+=lib/ctype.c
CSRC+=lib/dump_stack.c
CSRC+=lib/hexdump.c
CSRC+=lib/kasprintf.c
CSRC+=lib/klist.c
CSRC+=lib/kobject.c
CSRC+=lib/string.c
CSRC+=lib/vsprintf.c
CSRC+=lib/kstrtox.c

CSRC+=addition/mm_util.c
CSRC+=addition/bits.c
